export const cardList = [
  {
    id: 1,
    name: "A",
    image: "♣",
    category: "club",
    colorFamily: "black",
  },
  {
    id: 2,
    name: "2",
    image: "♣",
    category: "club",
    colorFamily: "black",
  },
  {
    id: 3,
    name: "3",
    image: "♣",
    category: "club",
    colorFamily: "black",
  },
  {
    id: 4,
    name: "4",
    image: "♣",
    category: "club",
    colorFamily: "black",
  },
  {
    id: 5,
    name: "5",
    image: "♣",
    category: "club",
    colorFamily: "black",
  },
  {
    id: 6,
    name: "6",
    image: "♣",
    category: "club",
    colorFamily: "black",
  },
  {
    id: 7,
    name: "7",
    image: "♣",
    category: "club",
    colorFamily: "black",
  },
  {
    id: 8,
    name: "8",
    image: "♣",
    category: "club",
    colorFamily: "black",
  },
  {
    id: 9,
    name: "9",
    image: "♣",
    category: "club",
    colorFamily: "black",
  },
  {
    id: 10,
    name: "10",
    image: "♣",
    category: "club",
    colorFamily: "black",
  },
  {
    id: 11,
    name: "J",
    image: "♣",
    category: "club",
    colorFamily: "black",
  },
  {
    id: 12,
    name: "Q",
    image: "♣",
    category: "club",
    colorFamily: "black",
  },
  {
    id: 13,
    name: "K",
    image: "♣",
    category: "club",
    colorFamily: "black",
  },
  {
    id: 14,
    name: "A",
    image: "♠",
    category: "spade",
    colorFamily: "black",
  },
  {
    id: 15,
    name: "2",
    image: "♠",
    category: "spade",
    colorFamily: "black",
  },
  {
    id: 16,
    name: "3",
    image: "♠",
    category: "spade",
    colorFamily: "black",
  },
  {
    id: 17,
    name: "4",
    image: "♠",
    category: "spade",
    colorFamily: "black",
  },
  {
    id: 18,
    name: "5",
    image: "♠",
    category: "spade",
    colorFamily: "black",
  },
  {
    id: 19,
    name: "6",
    image: "♠",
    category: "spade",
    colorFamily: "black",
  },
  {
    id: 20,
    name: "7",
    image: "♠",
    category: "spade",
    colorFamily: "black",
  },
  {
    id: 21,
    name: "8",
    image: "♠",
    category: "spade",
    colorFamily: "black",
  },
  {
    id: 22,
    name: "9",
    image: "♠",
    category: "spade",
    colorFamily: "black",
  },
  {
    id: 23,
    name: "10",
    image: "♠",
    category: "spade",
    colorFamily: "black",
  },
  {
    id: 24,
    name: "J",
    image: "♠",
    category: "spade",
    colorFamily: "black",
  },
  {
    id: 25,
    name: "Q",
    image: "♠",
    category: "spade",
    colorFamily: "black",
  },
  {
    id: 26,
    name: "K",
    image: "♠",
    category: "spade",
    colorFamily: "black",
  },
  {
    id: 27,
    name: "A",
    image: "♥",
    category: "heart",
    colorFamily: "red",
  },
  {
    id: 28,
    name: "2",
    image: "♥",
    category: "heart",
    colorFamily: "red",
  },
  {
    id: 29,
    name: "3",
    image: "♥",
    category: "heart",
    colorFamily: "red",
  },
  {
    id: 30,
    name: "4",
    image: "♥",
    category: "heart",
    colorFamily: "red",
  },
  {
    id: 31,
    name: "5",
    image: "♥",
    category: "heart",
    colorFamily: "red",
  },
  {
    id: 32,
    name: "6",
    image: "♥",
    category: "heart",
    colorFamily: "red",
  },
  {
    id: 33,
    name: "7",
    image: "♥",
    category: "heart",
    colorFamily: "red",
  },
  {
    id: 34,
    name: "8",
    image: "♥",
    category: "heart",
    colorFamily: "red",
  },
  {
    id: 35,
    name: "9",
    image: "♥",
    category: "heart",
    colorFamily: "red",
  },
  {
    id: 36,
    name: "10",
    image: "♥",
    category: "heart",
    colorFamily: "red",
  },
  {
    id: 37,
    name: "J",
    image: "♥",
    category: "heart",
    colorFamily: "red",
  },
  {
    id: 38,
    name: "Q",
    image: "♥",
    category: "heart",
    colorFamily: "red",
  },
  {
    id: 39,
    name: "K",
    image: "♥",
    category: "heart",
    colorFamily: "red",
  },
  {
    id: 40,
    name: "A",
    image: "♦",
    category: "diamond",
    colorFamily: "red",
    colorFamily: "red",
  },
  {
    id: 41,
    name: "2",
    image: "♦",
    category: "diamond",
    colorFamily: "red",
  },
  {
    id: 42,
    name: "3",
    image: "♦",
    category: "diamond",
    colorFamily: "red",
  },
  {
    id: 43,
    name: "4",
    image: "♦",
    category: "diamond",
    colorFamily: "red",
  },
  {
    id: 44,
    name: "5",
    image: "♦",
    category: "diamond",
    colorFamily: "red",
  },
  {
    id: 45,
    name: "6",
    image: "♦",
    category: "diamond",
    colorFamily: "red",
  },
  {
    id: 46,
    name: "7",
    image: "♦",
    category: "diamond",
    colorFamily: "red",
  },
  {
    id: 47,
    name: "8",
    image: "♦",
    category: "diamond",
    colorFamily: "red",
  },
  {
    id: 48,
    name: "9",
    image: "♦",
    category: "diamond",
    colorFamily: "red",
  },
  {
    id: 49,
    name: "10",
    image: "♦",
    category: "diamond",
    colorFamily: "red",
  },
  {
    id: 50,
    name: "J",
    image: "♦",
    category: "diamond",
    colorFamily: "red",
  },
  {
    id: 51,
    name: "Q",
    image: "♦",
    category: "diamond",
    colorFamily: "red",
  },
  {
    id: 52,
    name: "K",
    image: "♦",
    category: "diamond",
    colorFamily: "red",
  },
];

const getCardList = () => {
  const list = [
    "A",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10",
    "J",
    "Q",
    "K",
  ];
  const blackList = { "♠": "spade", "♣": "club" };
  const redList = { "♦": "diamond", "♥": "heart" };
  const list2 = { ...blackList, ...redList };
  let result = [],
    j = 0;
  Object.keys(list2).forEach((ele) => {
    const newList = list.map((item) => {
      return {
        id: ++j,
        name: item,
        image: ele,
        category: list2[ele],
        colorFamily: blackList[ele] ? "black" : "red",
      };
    });
    result = [...result, ...newList];
  });
  return result;
};

export const generatedCardList = getCardList();
console.log("Card List", generatedCardList);
